# BUILD STAGE
FROM maven:3-eclipse-temurin-17-alpine AS builder
COPY . build
WORKDIR  /build/src/main/resources/
RUN sed -i -e "s/\(spring.profiles.active=\).*/\1prod/" application.properties
RUN sed -i -e "s/\(spring.datasource.url=\).*/\1jdbc:postgresql:\\/\\/database:5432\\/demo/" application-prod.properties
WORKDIR /build
RUN mvn package -DskipTests -Pprod

# RUN STAGE
FROM openjdk:17
COPY --from=builder /build/target/demo-1.0.jar demo.jar
ENTRYPOINT ["java", "-jar","demo.jar"]
EXPOSE 8080