version: '3.1'
services:
  API:
    image: 'demo:prod-1.0'
    ports:
      - "8080:8080"
    depends_on:
      PostgreSQL:
        condition: service_healthy

  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=supersucretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5