# BUILD STAGE
FROM maven:3-eclipse-temurin-17-alpine AS builder
COPY . build
WORKDIR  /build/src/main/resources/
RUN sed -i -e "s/\(spring.profiles.active=\).*/\1dev/" application.properties
WORKDIR /build
CMD   ["mvn", "install", "-DskipTests", "-Pdev"]

# RUN STAGE
FROM openjdk:17
COPY --from=builder /build/target/demo-1.0.jar demo.jar
ENTRYPOINT ["java", "-jar","demo.jar"]
EXPOSE 8080